// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package category_item

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson773a3cfDecodeAvitoTest2CategoryItem(in *jlexer.Lexer, out *CategoryItems) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(CategoryItems, 0, 1)
			} else {
				*out = CategoryItems{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 CategoryItem
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson773a3cfEncodeAvitoTest2CategoryItem(out *jwriter.Writer, in CategoryItems) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v CategoryItems) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson773a3cfEncodeAvitoTest2CategoryItem(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CategoryItems) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson773a3cfEncodeAvitoTest2CategoryItem(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CategoryItems) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson773a3cfDecodeAvitoTest2CategoryItem(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CategoryItems) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson773a3cfDecodeAvitoTest2CategoryItem(l, v)
}
func easyjson773a3cfDecodeAvitoTest2CategoryItem1(in *jlexer.Lexer, out *CategoryItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			out.Title = string(in.String())
		case "href":
			out.Href = string(in.String())
		case "childes":
			if in.IsNull() {
				in.Skip()
				out.Childes = nil
			} else {
				in.Delim('[')
				if out.Childes == nil {
					if !in.IsDelim(']') {
						out.Childes = make([]CategoryItem, 0, 1)
					} else {
						out.Childes = []CategoryItem{}
					}
				} else {
					out.Childes = (out.Childes)[:0]
				}
				for !in.IsDelim(']') {
					var v4 CategoryItem
					(v4).UnmarshalEasyJSON(in)
					out.Childes = append(out.Childes, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson773a3cfEncodeAvitoTest2CategoryItem1(out *jwriter.Writer, in CategoryItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"href\":"
		out.RawString(prefix)
		out.String(string(in.Href))
	}
	if len(in.Childes) != 0 {
		const prefix string = ",\"childes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v5, v6 := range in.Childes {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CategoryItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson773a3cfEncodeAvitoTest2CategoryItem1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CategoryItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson773a3cfEncodeAvitoTest2CategoryItem1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CategoryItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson773a3cfDecodeAvitoTest2CategoryItem1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CategoryItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson773a3cfDecodeAvitoTest2CategoryItem1(l, v)
}
